---
version: '2'
services:
  db:
    image: 'mysql:5.7'
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
  web:
    build: .
    command: 'bin/ci start -b 0.0.0.0'
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
    environment:
      AUTH0_CLIENT_ID: 'OI3ctdXfGbgmwXEsxp9rOv33LvMAuMJB'
      AUTH0_CLIENT_SECRET: 'eUxHYUZ2RTdDZHZPNFFralctMkpEblEyWmxPQlJPSzJoZmp2QnAxVEtFRTZRdW9rblhmTnRfZ2RnTjkyVVNBcA'
    depends_on:
      - db